name: 'Validate Action'
description: 'Composite action to install Python dependencies'

runs:
  using: composite
  steps:
    # Step 1: List files to debug
    - name: List files in the composite action directory
      run: |
        echo "Listing files in the composite action directory:"
        ls -la ${{ github.action_path }}
      shell: bash

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip
        # Reference the requirements.txt file from the composite action repository
        cache-dependency-path: ${{ github.action_path }}/requirements.txt

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash


    - name: Run Compstate Validation
      shell: bash
      run: ${{ github.action_path }}/requirements.txt .
      

