name: Validate Action

runs:
  using: composite
  steps:
    # Step 1: Debug print to check if the file exists in the expected location
    - name: List files in the composite action
      run: |
        echo "Listing files in the composite action directory:"
        ls -la ${{ github.action_path }}
    
    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip
        # Use github.action_path to reference requirements.txt
        cache-dependency-path: ${{ github.action_path }}/requirements.txt

    # Step 3: Install Dependencies
    - name: Install Dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run Compstate Validation
      shell: bash
      run: ${{ github.action_path }}/validate.py .
