name: Validate Action

runs:
  using: composite
  steps:
  

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: ${{ github.action_path }}/requirements.txt

    - name: Install Dependencies
      shell: bash
      run: pip install requirements.txt

