name: 'Validate Action'
description: 'Composite action to install Python dependencies'

runs:
  using: composite
  steps:

      - name: Checkout main repository
        uses: actions/checkout@v4
      - name: Create symbolic link for requirements.txt
        run: ln -s ${{ github.action_path }}/requirements.txt
        shell: bash

    # Step 2: Set up Python
     - name: Set up Python
       uses: actions/setup-python@v5
        with:
         python-version: '3.10'
         cache: pip
         # Reference the requirements.txt file from the composite action repository
         cache-dependency-path: requirements.txt

    # Step 3: Install Dependencies
     - name: Install Dependencies
       run: pip install -r requirements.txt
     


     - name: Run Compstate Validation
       run: ${{ github.action_path }}/requirements.txt .
      

