name: 'Validate Action'
description: 'Action to validate and install dependencies'

runs:
  using: composite
  steps:
    # Step 1: Check files in the action repository
    - name: List files in the composite action directory
      run: |
        echo "Listing files in the composite action directory:"
        ls -la ${{ github.action_path }}
      shell: bash  # Specify shell for this step

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: ${{ github.action_path }}/requirements.txt
      shell: bash  # You can specify shell here too, though it's optional for actions like this

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash  # Specify shell for this step


    - name: Run Compstate Validation
      shell: bash
      run: ${{ github.action_path }}/requirements.txt .
